export const INITIALIZE_FAVOURITE ='INITIALIZE_FAVOURITE';
export const ADD_TO_FAVOURITE = "Add_To_Favourite";
export const REMOVE_FROM_FAVOURITE = "Remove_From_Favourite";
export const ADD_TO_CART = "Add_To_Cart";
export const REMOVE_FROM_CART = "Remove_From_Cart";
export const ADD_TO_ORDER_HISTORY = "Add_To_Order_History";
export const UPDATE_ITEM_QUANTITY = 'UPDATE_ITEM_QUANTITY';
export const INCREMENT_ITEM_QUANTITY = 'INCREMENT_ITEM_QUANTITY';
export const DECREMENT_ITEM_QUANTITY = 'DECREMENT_ITEM_QUANTITY';
export const INITIALIZE_CART = 'INITIALIZE_CART';
export const INITIALIZE_ORDER_HISTORY = 'INITIALIZE_ORDER_HISTORY';
export const DATE_INFO="DATE_INFO"